In [1]:
import numpy as np
import pandas as pd

In [2]:
train_df=pd.read_csv("train.csv",delimiter=",")

In [3]:
tr_y=train_df.values[:,4]

In [4]:
tr_y

array([482.26, 446.94, 452.56, ..., 437.65, 459.97, 444.42])

In [5]:
test=np.genfromtxt("test.csv",delimiter=",")
test_df=pd.DataFrame(test,columns=train_df.columns[0:train_df.shape[1]-1])

In [6]:
train_df.shape

(7176, 5)

In [7]:
test_df.shape

(2392, 4)

In [8]:
train_df.head()

# T      V       AP     RH      EP
0   8.58  38.38  1021.03  84.37  482.26
1  21.79  58.20  1017.21  66.74  446.94
2  16.64  48.92  1011.55  78.76  452.56
3  31.38  71.32  1009.17  60.42  433.44
4   9.20  40.03  1017.05  92.46  480.38

In [9]:
test_df.head()

# T      V       AP     RH
0  11.95  42.03  1017.58  90.89
1  12.07  38.25  1012.67  81.66
2  26.91  74.99  1005.64  78.98
3  20.58  39.53  1005.68  62.09
4  16.78  37.20  1011.97  68.94

In [10]:
test_df[' EP'] = np.nan

In [11]:
test_df.head()

# T      V       AP     RH   EP
0  11.95  42.03  1017.58  90.89  NaN
1  12.07  38.25  1012.67  81.66  NaN
2  26.91  74.99  1005.64  78.98  NaN
3  20.58  39.53  1005.68  62.09  NaN
4  16.78  37.20  1011.97  68.94  NaN

In [12]:
df=pd.concat([train_df,test_df],axis=0,ignore_index=True)
df

# T      V       AP     RH      EP
0      8.58  38.38  1021.03  84.37  482.26
1     21.79  58.20  1017.21  66.74  446.94
2     16.64  48.92  1011.55  78.76  452.56
3     31.38  71.32  1009.17  60.42  433.44
4      9.20  40.03  1017.05  92.46  480.38
...     ...    ...      ...    ...     ...
9563  29.49  69.71  1009.34  56.35     NaN
9564  27.69  65.34  1014.31  46.59     NaN
9565  24.32  66.25  1009.09  91.89     NaN
9566  23.49  42.80  1013.96  65.31     NaN
9567  21.76  60.27  1018.96  85.06     NaN

[9568 rows x 5 columns]

In [13]:
del df[' EP']

In [14]:
df.head()

# T      V       AP     RH
0   8.58  38.38  1021.03  84.37
1  21.79  58.20  1017.21  66.74
2  16.64  48.92  1011.55  78.76
3  31.38  71.32  1009.17  60.42
4   9.20  40.03  1017.05  92.46

In [15]:
from sklearn import preprocessing

In [16]:
df_scaled=preprocessing.scale(df)

In [17]:
scaled=pd.DataFrame(df_scaled, columns=df.columns[0:df.shape[1]])
scaled.head(5)

# T         V        AP        RH
0 -1.485656 -1.253287  1.308572  0.757630
1  0.287003  0.306455  0.665309 -0.449945
2 -0.404079 -0.423838 -0.287798  0.373370
3  1.573891  1.338938 -0.688574 -0.882837
4 -1.402458 -1.123440  0.638366  1.311758

In [18]:
scaled

# T         V        AP        RH
0    -1.485656 -1.253287  1.308572  0.757630
1     0.287003  0.306455  0.665309 -0.449945
2    -0.404079 -0.423838 -0.287798  0.373370
3     1.573891  1.338938 -0.688574 -0.882837
4    -1.402458 -1.123440  0.638366  1.311758
...        ...       ...       ...       ...
9563  1.320271  1.212239 -0.659947 -1.161613
9564  1.078728  0.868340  0.176968 -1.830129
9565  0.626505  0.939953 -0.702045  1.272716
9566  0.515127 -0.905453  0.118031 -0.547894
9567  0.282977  0.469355  0.959998  0.804892

[9568 rows x 4 columns]

In [19]:
train_scaled = scaled[0:7176]
test_scaled = scaled[7176:9568]

In [20]:
train_scaled

# T         V        AP        RH
0    -1.485656 -1.253287  1.308572  0.757630
1     0.287003  0.306455  0.665309 -0.449945
2    -0.404079 -0.423838 -0.287798  0.373370
3     1.573891  1.338938 -0.688574 -0.882837
4    -1.402458 -1.123440  0.638366  1.311758
...        ...       ...       ...       ...
7171 -1.386355 -1.304439  1.495489  0.423372
7172 -1.134076 -1.017201  1.412976 -0.782148
7173  1.361870  1.183122 -0.656579 -0.586936
7174 -0.440311 -0.000457  0.788237 -0.662966
7175  1.403469  0.608645 -0.432616 -1.736290

[7176 rows x 4 columns]

In [21]:
index=['EP']
df_=pd.DataFrame(tr_y,columns=index)

In [22]:
df = train_scaled.join(df_)
df.head(10)

# T         V        AP        RH      EP
0 -1.485656 -1.253287  1.308572  0.757630  482.26
1  0.287003  0.306455  0.665309 -0.449945  446.94
2 -0.404079 -0.423838 -0.287798  0.373370  452.56
3  1.573891  1.338938 -0.688574 -0.882837  433.44
4 -1.402458 -1.123440  0.638366  1.311758  480.38
5  0.961982  1.174465  0.003523 -1.537653  436.36
6 -1.364884 -1.062844  1.778390  0.388439  485.36
7 -1.374278 -1.004610  1.047562  0.608310  481.59
8  1.526924  1.202795 -0.924325 -0.640363  432.56
9 -0.189374  0.381216 -0.212021  0.759685  449.48

In [23]:
train_data=train_scaled.values
train_data

array([[-1.48565576e+00, -1.25328692e+00,  1.30857232e+00,
         7.57629905e-01],
       [ 2.87002787e-01,  3.06455193e-01,  6.65309346e-01,
        -4.49945221e-01],
       [-4.04079084e-01, -4.23837783e-01, -2.87797566e-01,
         3.73370321e-01],
       ...,
       [ 1.36186993e+00,  1.18312154e+00, -6.56579216e-01,
        -5.86936159e-01],
       [-4.40310561e-01, -4.56725914e-04,  7.88236563e-01,
        -6.62966130e-01],
       [ 1.40346903e+00,  6.08645389e-01, -4.32615931e-01,
        -1.73629014e+00]])

In [24]:

test_data=test_scaled.values
test_data

array([[-1.03343325, -0.96604884,  0.72761492,  1.20422036],
       [-1.01733038, -1.26351731, -0.09919691,  0.57200718],
       [ 0.97405894,  1.62775035, -1.28300284,  0.38843932],
       ...,
       [ 0.62650514,  0.93995287, -0.70204545,  1.27271583],
       [ 0.5151269 , -0.90545341,  0.11803064, -0.54789374],
       [ 0.28297707,  0.4693546 ,  0.95999788,  0.80489178]])

In [25]:
def step_grad(points, learn_rate, M):
    r = points.shape[0]
    c = points.shape[1]
    new_M = np.zeros(c)
    
    for i in range(r):
        x = points[i, 0:c-1]
        x = np.append(x, 1)
        y = points[i,c-1]
        for j in range(c):
            new_M[j] += (-2/r) * (y - (M * x).sum()) * x[j]
        M = M - (learn_rate * new_M)
    return M

In [26]:
def gd(points, learn_rate, num_iter):
    c = points.shape[1]
    M = np.zeros(c)
    
    for i in range(num_iter):
        M = step_grad(points, learn_rate, M)
        print(i, "cost = ", cost(points, M))

    return M

In [27]:
def cost(points, M):
    total_cost = 0
    r = points.shape[0]
    c = points.shape[1]
    
    for i in range(r):
        x = points[i,0:c-1]
        x = np.append(x, 1)
        y = points[i,c-1]
        total_cost += (y - (M * x).sum()) ** 2  
    total_cost = (1/r) * total_cost
    return total_cost


In [28]:
def run():
    learning_rate = 0.0001
    num_iterations = 50
    m = gd(train_data, learning_rate, num_iterations)
    
    return m[0:train_data.shape[1]-1],m[train_data.shape[1]-1]

In [29]:
m,c=run()


0 cost =  0.7783473927884373
1 cost =  0.7255667787750425
2 cost =  0.6949914365712948
3 cost =  0.6723704137601995
4 cost =  0.6548600866014482
5 cost =  0.6410026299839271
6 cost =  0.6299540453324058
7 cost =  0.6211149534923222
8 cost =  0.6140345728433009
9 cost =  0.608359930797991
10 cost =  0.6038109027078347
11 cost =  0.600163756176506
12 cost =  0.5972394024930021
13 cost =  0.5948943648039429
14 cost =  0.593013666827449
15 cost =  0.5915051656827793
16 cost =  0.590295017553968
17 cost =  0.5893240442671239
18 cost =  0.5885448207378586
19 cost =  0.5879193402623698
20 cost =  0.5874171432207596
21 cost =  0.5870138173954026
22 cost =  0.5866897962311686
23 cost =  0.5864293959193905
24 cost =  0.5862200438839357
25 cost =  0.5860516606428646
26 cost =  0.5859161645618991
27 cost =  0.5858070750677545
28 cost =  0.5857191947430731
29 cost =  0.585648354616045
30 cost =  0.5855912100766587
31 cost =  0.5855450773509842
32 cost =  0.5855078024675779
33 cost =  0.585477656254

In [30]:
print("m = ", m)
print("c = ", c)

m =  [-1.10656442  0.51187129 -0.25018605]
c =  -0.008230682267050697


In [31]:
def predict(points, m, c):
    r = points.shape[0]
    pred = np.zeros(r)
    
    for i in range(r):
        X = points[i,:]
        pred[i] = (m * X).sum() + c
        
    return pred

In [32]:
predictions = predict(test_data, m, c)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [ ]:
np.savetxt("predictions.csv",predictions,fmt="%.5f")

In [ ]:
predictions